# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ondřej Chwiedziuk
email: ondra@chwiedziuk.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website showcasing recipes, projects, studies, research, photography, and other random stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chwiedziuk.cz" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: ondrej-chwiedziuk
github_username:  ondrachwiedziuk

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jektex
  - jekyll-sitemap

# JekTeX configuration
jektex:
  cache_dir: ".jektex-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\R", "\\mathbb{R}"]
    - ["\\N", "\\mathbb{N}"]
    - ["\\Z", "\\mathbb{Z}"]
    - ["\\C", "\\mathbb{C}"]

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:name/
  galleries:
    output: true
    permalink: /photos/:name/

# Header pages for navigation
header_pages:
  - study.md
  - research.md
  - projects.md
  - photos.md
  - recipes.md

# Minima settings
minima:
  date_format: "%b %-d, %Y"

# Include files that should be copied without processing
include:
  - googlee10a682c15c025b1.html

# Exclude specific auto-generated files that may appear
exclude:
  - assets/images/README.md
  - _layouts/home.html
  - assets/photos/originals/
  - GALLERY_README.md
  - .jektex-cache
